[package]
name = "hinode-up"
version = "0.1.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
csv = "1.3.0"
ruzstd = "0.7.1"
vibrato = "0.5.1"
wasm-bindgen = "0.2.93"